import { PrismaService } from 'prisma/services/prisma.service';
import { SpellLore } from 'src/entities/spell-lore.entity';
import { Spell } from 'src/entities/spell.entity';
import { Skill } from 'src/entities/skill.entity';
import { SkillList } from 'src/entities/skill-list.entity';
import { Advancement } from 'src/entities/advancement.entity';
import { Injury } from 'src/entities/injury.entity';
import { Equipment } from 'src/entities/equipment.entity';
import { SuperNaturalAbility } from 'src/entities/super-natural-ability.entity';
import { Faction } from 'src/modules/warbands/entities/faction.entity';
import { BaseFigure } from 'src/entities/base-figure.entity';
import { Modifier } from 'src/entities/modifier.entity';
import { SpellLoresQueryDto } from '../../dto/spell-lores-query.dto';
import { SpellQueryDto } from '../../dto/spell-query.dto';
import { SkillQueryDto } from '../../dto/skill-query.dto';
import { SkillListsQueryDto } from '../../dto/skill-lists-query.dto';
import { AdvancementQueryDto } from '../../dto/advancement-query.dto';
import { InjuryQueryDto } from '../../dto/injury-query.dto';
import { EquipmentQueryDto } from '../../dto/equipment-query.dto';
import { SuperNaturalAbilityQueryDto } from '../../dto/super-natural-ability-query.dto';
import { FactionQueryDto } from '../../dto/faction-query.dto';
import { BaseFigureQueryDto } from '../../dto/base-figure-query.dto';
import { ModifierQueryDto } from '../../dto/modifier-query.dto';
import { QueriesRepository } from '../queries.repository';
import { EquipmentToWarbandSoldier } from 'src/modules/soldiers/entities/equipment-to-warband-soldier.entity';
import { EquipmentToVault } from 'src/modules/warbands/entities/equipment-to-vault.entity';
export declare class QueriesPrismaRepository implements QueriesRepository {
    private readonly prisma;
    constructor(prisma: PrismaService);
    findAllSpellLores(spellLoresQueryDto: SpellLoresQueryDto): Promise<SpellLore[]>;
    findAllSpells(spellQueryDto: SpellQueryDto): Promise<Spell[]>;
    findSpellByslug(slug: string): Promise<Spell>;
    findSpellLoreByslug(slug: string): Promise<SpellLore>;
    findAllSkills(dto: SkillQueryDto): Promise<Skill[]>;
    findSkillByslug(slug: string): Promise<Skill>;
    findAllSkillLists(dto: SkillListsQueryDto): Promise<SkillList[]>;
    findSkillListByslug(slug: string): Promise<SkillList>;
    findAllAdvancements(dto: AdvancementQueryDto): Promise<Advancement[]>;
    findAdvancementByslug(slug: string): Promise<Advancement>;
    findAllInjuries(dto: InjuryQueryDto): Promise<Injury[]>;
    findInjuryByslug(slug: string): Promise<Injury>;
    findAllEquipments(dto: EquipmentQueryDto): Promise<Equipment[]>;
    findEquipmentByslug(slug: string): Promise<Equipment>;
    findAllSuperNaturalAbilities(dto: SuperNaturalAbilityQueryDto): Promise<SuperNaturalAbility[]>;
    findSuperNaturalAbilityByslug(slug: string): Promise<SuperNaturalAbility>;
    findAllModifiers(dto: ModifierQueryDto): Promise<Modifier[]>;
    findModifierByslug(slug: string): Promise<Modifier>;
    findAllFactions(dto: FactionQueryDto): Promise<Faction[]>;
    findFactionByslug(slug: string): Promise<Faction>;
    findAllBaseFigures(dto: BaseFigureQueryDto): Promise<BaseFigure[]>;
    findBaseFigureByslug(slug: string): Promise<BaseFigure>;
    findEquipmentToWarbandSoldierById(id: string): Promise<EquipmentToWarbandSoldier>;
    findEquipmentToVaultById(id: string): Promise<EquipmentToVault>;
}
