import { SoldiersService } from './soldiers.service';
import { UpdateSoldierDto } from './dto/update-soldier.dto';
import { PromoteHeroDto } from './dto/promote-hero.dto';
export declare class SoldiersController {
    private readonly soldiersService;
    constructor(soldiersService: SoldiersService);
    findOne(id: string): Promise<import("./entities/warband-soldier.entity").WarbandSoldier>;
    addEquipmentToSoldier(soldierId: string, warbandVaultItemId: string): Promise<void>;
    removeEquipmentFromSoldier(soldierId: string, warbandToSoldierItemId: string): Promise<void>;
    equipItemToSoldier(equipmentToWarbandSoldierId: string, slot: string): Promise<void>;
    unequipItemFromSoldier(equipmentToWarbandSoldierId: string): Promise<void>;
    unequipSlotFromSoldier(soldierId: string, slot: string): Promise<void>;
    addSpellToSoldier(soldierId: string, spellSlug: string): Promise<void>;
    removeSpellFromSoldier(warbandSoldierSpellId: string): Promise<void>;
    addSkillToSoldier(soldierId: string, skillSlug: string): Promise<void>;
    removeSkillFromSoldier(skillToWarbandSoldierId: string): Promise<void>;
    killSoldier(soldierId: string): Promise<void>;
    undoSoldier(soldierId: string): Promise<void>;
    addInjuryToSoldier(soldierId: string, injurySlug: string): Promise<void>;
    removeInjuryFromSoldier(injuryToWarbandSoldierId: string): Promise<void>;
    addAdvancementToSoldier(soldierId: string, advancementSlug: string): Promise<void>;
    removeAdvancementFromSoldier(advancementToWarbandSoldierId: string): Promise<void>;
    addSuperNaturalAbilityToSoldier(soldierId: string, superNaturalAbilitySlug: string): Promise<void>;
    removeSuperNaturalAbilityFromSoldier(superNaturalAbilityToWarbandSoldierId: string): Promise<void>;
    updateSoldier(soldierId: string, updateSoldierDto: UpdateSoldierDto): Promise<void>;
    fortifySpell(spellToWarbandSoldierId: string): Promise<void>;
    unfortifySpell(spellToWarbandSoldierId: string): Promise<void>;
    promoteToHero(soldierId: string, promoteHeroDto: PromoteHeroDto): Promise<void>;
    promoteLeader(soldierId: string): Promise<void>;
    toggleSoldierActive(soldierId: string): Promise<void>;
}
