import { SpellQueryDto } from './dto/spell-query.dto';
import { SpellLoresQueryDto } from './dto/spell-lores-query.dto';
import { SkillQueryDto } from './dto/skill-query.dto';
import { SkillListsQueryDto } from './dto/skill-lists-query.dto';
import { AdvancementQueryDto } from './dto/advancement-query.dto';
import { InjuryQueryDto } from './dto/injury-query.dto';
import { EquipmentQueryDto } from './dto/equipment-query.dto';
import { SuperNaturalAbilityQueryDto } from './dto/super-natural-ability-query.dto';
import { ModifierQueryDto } from './dto/modifier-query.dto';
import { FactionQueryDto } from './dto/faction-query.dto';
import { BaseFigureQueryDto } from './dto/base-figure-query.dto';
import { QueriesRepository } from './repositories/queries.repository';
export declare class QueriesService {
    private readonly repo;
    constructor(repo: QueriesRepository);
    findAllSpellLores(dto: SpellLoresQueryDto): Promise<import("../../entities/spell-lore.entity").SpellLore[]>;
    findAllSpells(dto: SpellQueryDto): Promise<import("../../entities/spell.entity").Spell[]>;
    findSpellByslug(slug: string): Promise<import("../../entities/spell.entity").Spell>;
    findSpellLoreByslug(slug: string): Promise<import("../../entities/spell-lore.entity").SpellLore>;
    findAllSkills(dto: SkillQueryDto): Promise<import("../../entities/skill.entity").Skill[]>;
    findSkillByslug(slug: string): Promise<import("../../entities/skill.entity").Skill>;
    findAllSkillLists(dto: SkillListsQueryDto): Promise<import("../../entities/skill-list.entity").SkillList[]>;
    findSkillListByslug(slug: string): Promise<import("../../entities/skill-list.entity").SkillList>;
    findAllAdvancements(dto: AdvancementQueryDto): Promise<import("../../entities/advancement.entity").Advancement[]>;
    findAdvancementByslug(slug: string): Promise<import("../../entities/advancement.entity").Advancement>;
    findAllInjuries(dto: InjuryQueryDto): Promise<import("../../entities/injury.entity").Injury[]>;
    findInjuryByslug(slug: string): Promise<import("../../entities/injury.entity").Injury>;
    findAllEquipments(dto: EquipmentQueryDto): Promise<import("../../entities/equipment.entity").Equipment[]>;
    findEquipmentByslug(slug: string): Promise<import("../../entities/equipment.entity").Equipment>;
    findAllSuperNaturalAbilities(dto: SuperNaturalAbilityQueryDto): Promise<import("../../entities/super-natural-ability.entity").SuperNaturalAbility[]>;
    findSuperNaturalAbilityByslug(slug: string): Promise<import("../../entities/super-natural-ability.entity").SuperNaturalAbility>;
    findAllModifiers(dto: ModifierQueryDto): Promise<import("../../entities/modifier.entity").Modifier[]>;
    findModifierByslug(slug: string): Promise<import("../../entities/modifier.entity").Modifier>;
    findAllFactions(dto: FactionQueryDto): Promise<import("../warbands/entities/faction.entity").Faction[]>;
    findFactionByslug(slug: string): Promise<import("../warbands/entities/faction.entity").Faction>;
    findAllBaseFigures(dto: BaseFigureQueryDto): Promise<import("../../entities/base-figure.entity").BaseFigure[]>;
    findBaseFigureByslug(slug: string): Promise<import("../../entities/base-figure.entity").BaseFigure>;
    findEquipmentToWarbandSoldierById(id: string): Promise<import("../soldiers/entities/equipment-to-warband-soldier.entity").EquipmentToWarbandSoldier>;
    findEquipmentToVaultById(id: string): Promise<import("../warbands/entities/equipment-to-vault.entity").EquipmentToVault>;
}
