import type { Role as PrismaRole } from '@prisma/client';
import { FigureToAvaiableEquipment } from './figure-to-avaiable-equipment.entity';
import { FigureToSkillList } from './figure-to-skill-list.entity';
import { FigureToSpellLore } from './figure-to-spell-lore.entity';
import { MercenaryStartingEquipment } from './mercenary-starting-equipment.entity';
import { LegendStartingEquipment } from './legend-starting-equipment.entity';
import { LegendStartingSpells } from './legend-starting-spells.entity';
import { LegendStartingSkills } from './legend-starting-skills.entity';
export type Role = PrismaRole;
export declare class BaseFigure {
    id: string;
    name: string;
    role: Role;
    slug: string;
    lore: string;
    avaiability: string[];
    exclusions: string[];
    quality: number;
    canGetMutations: boolean;
    canGetSacredMarks: boolean;
    canGetBlessings: boolean;
    race?: string | null;
    factionSlug?: string | null;
    cost: number;
    movement: number;
    fight: number;
    shoot: number;
    armour: number;
    will: number;
    health: number;
    strength: number;
    equipmentSlots: number;
    startingXp?: number | null;
    createdAt: Date;
    specialRules: unknown;
    naturalAttacks?: unknown;
    avaiableEquipment?: FigureToAvaiableEquipment[];
    skillLists?: FigureToSkillList[];
    spellLores?: FigureToSpellLore[];
    mercenaryStartingEquipment?: MercenaryStartingEquipment[];
    legendStartingEquipment?: LegendStartingEquipment[];
    legendStartingSpells?: LegendStartingSpells[];
    legendStartingSkills?: LegendStartingSkills[];
}
